import api, { adminApi } from './api';
export const getZones = (branch) => adminApi.get('/admin/delivery-zones', { params: branch ? { branch } : {} }).then((r) => r.data);
export const getZonesPublic = (branch) => api.get('/delivery-zones', { params: branch ? { branch } : {} }).then((r) => r.data);
export const createZone = (data) => adminApi.post('/admin/delivery-zones', data).then((r) => r.data);
export const updateZone = (id, data) => adminApi.put(`/admin/delivery-zones/${id}`, data).then((r) => r.data);
export const deleteZone = (id) => adminApi.delete(`/admin/delivery-zones/${id}`).then((r) => r.data);
export const getReps = (branch) => adminApi.get('/admin/delivery-reps', { params: branch ? { branch } : {} }).then((r) => r.data);
export const createRep = (data) => adminApi.post('/admin/delivery-reps', data).then((r) => r.data);
export const updateRep = (id, data) => adminApi.put(`/admin/delivery-reps/${id}`, data).then((r) => r.data);
export const deleteRep = (id) => adminApi.delete(`/admin/delivery-reps/${id}`).then((r) => r.data);
